name: aws_ebs

on:
  workflow_call:
    inputs:
      aws_ebs_application_name:
        required: true
        type: string
      aws_ebs_environment_name:
        required: true
        type: string
      aws_s3_bucket_name:
        required: true
        type: string
      build_type:
        required: true
        type: string
      slack_channel_ids:
        required: false
        type: string
      workflow_environment:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      SLACK_BOT_TOKEN:
        required: false

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_EBS_APPLICATION_NAME: ${{ inputs.aws_ebs_application_name }}
  AWS_EBS_ENVIRONMENT_NAME: ${{ inputs.aws_ebs_environment_name }}
  AWS_S3_BUCKET_NAME: ${{ inputs.aws_s3_bucket_name }}
  BUILD_DIRECTORY: ./target
  BUILD_TYPE: ${{ inputs.build_type }}
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  SLACK_CHANNEL_IDS: ${{ inputs.slack_channel_ids }}
  SOURCE_DIRECTORY: ./app
  SOURCE_HOOKS_SUBDIRECTORY: ./.github/hooks
  WORKFLOW_ENVIRONMENT: ${{ inputs.workflow_environment }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Logging run context
        run: |
          echo "user: ${{ github.actor }},
          deploying branch: ${{ github.ref }},
          to EBS environment: $AWS_EBS_APPLICATION_NAME [$AWS_EBS_ENVIRONMENT_NAME]"
      - name: Checking-out remote scripts
        uses: actions/checkout@v3
        with:
          repository: oshopgiri/deploy_actions
          ref: master
          path: ./
      - name: Setting-up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Checking-out current branch
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: ${{ env.SOURCE_DIRECTORY }}
      - name: Setting-up JDK
        if: env.BUILD_TYPE == 'war'
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
      - name: Making hooks executable
        run: |
          for script in $(find $SOURCE_HOOKS_SUBDIRECTORY -name '*.sh');
          do
            chmod +x $script
          done
        working-directory: ${{ env.SOURCE_DIRECTORY }}
      - name: Running pre-build hook
        run: |
          if test -f "$SOURCE_HOOKS_SUBDIRECTORY/pre_build.sh"; then
            $SOURCE_HOOKS_SUBDIRECTORY/pre_build.sh $WORKFLOW_ENVIRONMENT
          fi
        working-directory: ${{ env.SOURCE_DIRECTORY }}
      - name: Building
        run: |
          mkdir -p $BUILD_DIRECTORY
          ruby ./bin/build.rb
      - name: Triggering deploy
        if: success()
        run: |
          ruby ./bin/aws/ebs/deploy.rb
