name: ebs

on:
  workflow_call:
    inputs:
      action_environment:
        required: false
        type: string
      aws_ebs_environment_name:
        required: true
        type: string
      slack_channel_ids:
        required: false
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      SLACK_BOT_TOKEN:
        required: false

env:
  ACTION_ENVIRONMENT: ${{ inputs.action_environment }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_EBS_ENVIRONMENT_NAME: ${{ inputs.aws_ebs_environment_name }}
  GITHUB_ACTION_NAME: ebs_fetch_logs
  LOG_FILE_PATH: ./${{ inputs.aws_ebs_environment_name }}_logs.zip
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  SLACK_CHANNEL_IDS: ${{ inputs.slack_channel_ids }}

jobs:
  fetch_logs:
    runs-on: ubuntu-latest
    steps:
      - name: Logging run context
        run: |
          echo "user: ${{ github.actor }},
          fetching logs for EBS environment: $AWS_EBS_ENVIRONMENT_NAME"
      - name: Checking-out remote scripts
        uses: actions/checkout@v3
        with:
          repository: oshopgiri/deploy_actions
          ref: master
      - name: Setting-up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Fetching logs
        run: ruby ./bin/ebs_fetch_logs.rb
      - name: Publishing logs as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.AWS_EBS_ENVIRONMENT_NAME }}
          path: ${{ env.LOG_FILE_PATH }}
      - name: Notify failure
        if: failure()
        run: ruby ./bin/slack_notify_failed_action.rb
